name: CE

on:
  workflow_call:

jobs:

  job-1:
    name: Job-1
    runs-on: ubuntu-latest

    steps:
      - name: Run simple task
        run: echo "This is a simple job."

  job-2:
    name: Test on ${{ matrix.time }}
    needs: job-1
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        time: [300, 600, 900]

    steps:

      - name: Sleep for ${{ matrix.time }} seconds
        run: echo "Sleeping for ${{ matrix.time }} seconds..." && sleep ${{ matrix.time }}

      - name: Run tests
        run: echo "Running tests..."

  post-check:
    name: Post-check (runs after matrix)
    runs-on: ubuntu-latest
    needs: job-2
    steps:
      - name: Summary
        run: echo "All matrix test jobs completed."
