name: DD

on:
  workflow_dispatch:

jobs:

  job-1:
    name: Simple Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run simple task
        run: echo "This is a simple job."

  job-2:
    name: Test on Node ${{ matrix.node-version }}
    needs: job-1
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        time: [30, 600, 900]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sleep for ${{ matrix.time }} seconds
        run: echo "Sleeping for ${{ matrix.time }} seconds..." && sleep ${{ matrix.time }}

      - name: Call  CE action
        uses: ./.github/ce.yml        

  post-check:
    name: Post-check 
    runs-on: ubuntu-latest
    needs: job-2
    steps:
      - name: Summary
        run: echo "All matrix test jobs completed."
